# LagReport Config - Version 2.5
# Special thanks to EduUuTriste for suggesting customizable TPS thresholds,
# optional event toggles, and the Chunk-Specific Anti-Overflow system.

webhook-url: "URL_HARDWARE"
slimefun-webhook-url: "URL_SLIMEFUN"

# Choose your language: pt or en
language: "pt"

# Performance settings
settings:
  tps-min-threshold: 15.0
  tps-max-threshold: 19.5
  clear-drops-on-activation: false

# Advanced Anti-Lag (Entity & Redstone focus)
# Scans for chunks with too many entities to prevent overflow
breaker-settings:
  activation-tps: 16.0
  max-entities-per-chunk: 500
  clean-radius: 1
  break-material: REDSTONE_WIRE

# Which systems should be disabled during HALT ON mode?
halt-on-settings:
  disable-redstone: true
  disable-mob-spawn: true
  disable-explosions: true
  disable-mob-ai: true
  disable-gravity-blocks: true
  disable-liquid-flow: true
  disable-pistons: true
  disable-hoppers: true
  disable-crop-growth: true
  disable-portals: true
  disable-enderman-teleport: true
  disable-villager-trading: true
  disable-armor-stand-interact: true
  disable-leaf-decay: true
  disable-fire-spread: true
  disable-ice-melt: true
  disable-ice-form: true
  disable-grass-spread: true
