name: LagReport
version: '2.3'
main: com.comonier.lagreport.LagReport
api-version: '1.21'
author: Comonier
description: Audit mode and emergency anti-lag system with Discord integration.
commands:
  lagreport:
    description: Main command for LagReport management.
    usage: /lagreport [reload|test|simulate]
    permission: lagreport.admin
  sftimings:
    description: Sends Slimefun performance report to Discord.
    usage: /sftimings [test]
    permission: lagreport.admin
permissions:
  lagreport.admin:
    description: Allows administrative access to LagReport commands and audits.
    default: op
