name: LagReport
version: '1.0'
main: com.comonier.lagreport.LagReport
api-version: '1.21'
author: Comonier
description: Relatorio de consumo e sistema de emergencia anti-lag.
commands:
  lagreport:
    description: Comando principal para gerenciar o plugin.
    usage: /lagreport [reload|test]
    permission: lagreport.admin
permissions:
  lagreport.admin:
    description: Permite usar os comandos do LagReport.
    default: op
